server:
  port: 8080
logging:
  level:
    org.springframework.web: ERROR
    fr.apside.formation: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher