server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:formationdb
    username: sa
    password:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.springframework: INFO
    fr.apside.formation: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


user:
  default:
    uppercaseLogin: false
    generatePassword: false
    passwordByDefault: azerty
